[phases.setup]
nixPkgs = ["python3"]

[phases.install]
cmds = ["echo 'Static site - no installation needed'"]

[phases.build]
cmds = ["echo 'Static site - no build needed'"]

[start]
cmd = "python3 -m http.server $PORT" 